nguage: ruby
rvm:
  - 2.2.5
env:
  - "RAILS_VERSION=3.2.22"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.0"
cache: bundler
install: bundle update
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: ./ci/test.sh
