language: ruby
dist: xenial
services:
  - xvfb

rvm:
  - 2.2.5
  - 2.6.3

matrix:
  include:
    - rvm: 2.2.5
      env: RAILS_VERSION=3.2.22
    - rvm: 2.2.5
      env: RAILS_VERSION=4.2.0
    - rvm: 2.6.3
      env: RAILS_VERSION=5.2.0
    - rvm: 2.6.3
      env: RAILS_VERSION=6.0.0

addons:
  apt:
    packages:
      # build dependencies for capybara-webkit
      - g++
      - qt5-default
      - libqt5webkit5-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-tools
      - gstreamer1.0-x

cache:
  directories:
    - /home/travis/.rvm/gems

install: ./ci/build.sh

script: ./ci/test.sh

jobs:
  include:
    - stage: publish components
      script: 'cd rswag-api'
      deploy:
        gemspec: rswag-api.gemspec
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true

    - stage: publish components
      script: 'cd rswag-specs'
      deploy:
        gemspec: rswag-specs.gemspec
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true

    - stage: publish components
      script: 'cd rswag-ui'
      deploy:
        gemspec: rswag-ui.gemspec
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        skip_cleanup: true
        on:
          branch: master
          tags: true

    - stage: publish rswag
      script: 'cd rswag'
      deploy:
        gemspec: rswag.gemspec
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true
